import base64
from openai import OpenAI

# =================================================================
# VISION UTILITY: IMAGE-TO-TEXT CONVERSION
# =================================================================

def describe_image(image_path, api_key):
    """
    Analyzes an image file using GPT-4o-mini's vision capabilities.
    
    This function converts visual data into descriptive text so that 
    non-textual PDF elements (like charts or workflows) can be indexed 
    and queried by the RAG system.
    
    Parameters:
    - image_path (str): The local path to the image file to be processed.
    - api_key (str): The OpenAI API key for authentication.
    """
    
    # 1. INITIALIZE CLIENT
    # We initialize the client inside the function to ensure the API key 
    # is always fresh and scope-specific.
    client = OpenAI(api_key=api_key)

    # 2. IMAGE ENCODING
    # OpenAI's Vision API requires images to be sent as Base64 strings.
    # We open the image in 'rb' (read binary) mode, encode it, and 
    # convert it to a UTF-8 string.
    with open(image_path, "rb") as image_file:
        encoded_image = base64.b64encode(image_file.read()).decode('utf-8')

    # 3. MULTI-MODAL API CALL
    # We send both a text instruction (the prompt) and the image data.
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text", 
                        "text": "Describe this image in detail. If it is a chart, explain the data. If it is a diagram, explain the steps."
                    },
                    {
                        "type": "image_url", 
                        "image_url": {"url": f"data:image/jpeg;base64,{encoded_image}"}
                    }
                ],
            }
        ],
    )
    
    # 4. EXTRACT DESCRIPTION
    # Return the text generated by the model to be saved into the vector database.
    return response.choices[0].message.content